auth:
  providers:
    github:
      development:
        clientId: your-github-oauth-client-id
        clientSecret: your-github-oauth-client-secret
        signIn:
          resolvers:
            - resolver: usernameMatchingUserEntityName
              dangerouslyAllowSignInWithoutUserInCatalog: true

techRadar:
  url: https://raw.githubusercontent.com/jacobduijzer/bimcollab-backstage-demo/refs/heads/main/demo/custom-tech-radar.json
