apiVersion: backstage.io/v1alpha1
kind: Domain
metadata:
  name: space-admin
  description: Space administration
  annotations:
    backstage.io/techdocs-ref: dir:.
  links:
    - url: http://example.com/domain/artists/
      title: Domain Readme
    - url: http://example.com/domains/artists/dashboard
      title: Domain Metrics Dashboard
      icon: dashboard
spec:
  owner: group:admin

---
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: space-management
  description: Complete space management system
spec:
  owner: group:admin
  domain: space-admin

---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: space-management-service
  description: Space Management API
  tags:
    - dotnet
    - csharp
    - webapi
    - temporal
spec:
  type: service
  lifecycle: production
  owner: group:admin
  system: space-management
  providesApis:
    - space-management-api

---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: space-management-api
  description: Service to manage spaces
  links:
    - url: https://backstage-demo-weather-api.azurewebsites.net/swagger
      title: Test Api
      icon: dashboard
spec:
  type: openapi
  lifecycle: production
  owner: group:admin
  system: space-management
  #definition: 
  #  $text: https://backstage-demo-weather-api.azurewebsites.net/swagger/v1/swagger.json
