apiVersion: backstage.io/v1alpha1
kind: Domain
metadata:
  name: space-admin
  title: Space Admin Bounded Context
  description: Space administration bounded context
  annotations:
    backstage.io/techdocs-ref: dir:.
  links:
    - url: http://example.com/bounded-contexts/space-admin/
      title: Bounded Context Readme
    - url: http://example.com/bounded-contexts/space-admin/dashboard
      title: Bounded Context Metrics Dashboard
      icon: dashboard
spec:
  owner: group:admin
