site_name: 'Space Administration'
site_description: 'All documentation regarding the Space Administration.'
repo_url: https://github.com/jacobduijzer/bimcollab-backstage-demo/tree/main/demo/bounded-context/space-admin
edit_uri: edit/master/docs

plugins:
  - techdocs-core
  
nav:
  - Home: 'index.md'
  - Overview: 'overview.md'
