---
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: product
  description: The product department
spec:
  type: business-unit
  profile:
    displayName: Product
    email: product@example.com
  children: []
  members: []

---
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: development
  description: The development department
spec:
  type: business-unit
  profile:
    displayName: Development
    email: development@example.com
  children: [admin, twin]
  members: []

---
# https://backstage.io/docs/features/software-catalog/descriptor-format#kind-group
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: admin
spec:
  type: team
  profile:
    displayName: Admin
    email: admin@example.com
    picture: https://example.com/groups/bu-infrastructure.jpeg
  children: []

---
# https://backstage.io/docs/features/software-catalog/descriptor-format#kind-group
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: twin
spec:
  type: team
  profile:
    displayName: Twin
    email: twin@example.com
    picture: https://example.com/groups/bu-infrastructure.jpeg
  children: []

---
# https://backstage.io/docs/features/software-catalog/descriptor-format#kind-user
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: jacob
spec:
  memberOf: [admin, twin]
  profile:
    displayName: Jacob Duijzer

---
# https://backstage.io/docs/features/software-catalog/descriptor-format#kind-user
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: demo 
spec:
  memberOf: [product]
  profile:
    displayName: Demo User

