site_name: 'Document Management'
site_description: 'All documentation regarding document management'
repo_url: https://github.com/jacobduijzer/bimcollab-backstage-demo/tree/main/demo/bounded-context/document-management
edit_uri: edit/master/docs

plugins:
  - techdocs-core
  
nav:
  - Home: 'index.md'
  - Overview: 'overview.md'
